export type Article = {
  slug: string
  title: string
  category: string
  excerpt: string
  image: string
  author: string
  authorImage: string
  date: string
  content: string[]
}

export const articles: Article[] = [
  {
    slug: "how-we-built-u-lens",
    title: "How We Built U-Lens: Turning 45,000 Daily Store Scans into Absolute Retail Control",
    category: "Articles",
    excerpt:
      "The story of how we designed, architected, and deployed U-Lens — from solving sub-second computer vision constraints to automating field force payroll.",
    image: "/images/ulens-mockup.png",
    author: "Albid Nawar",
    authorImage: "/images/design-mode/63407fbdc2d4ac5270385fd4_home-he.png",
    date: "Aug 12, 2026",
    content: [
      "As a product manager, there is a specific kind of chaos you only encounter when building software for general trade retail in emerging markets.",
      "Picture hundreds of thousands of micro-stores scattered across dense urban alleys and remote rural roads. Millions of dollars poured into point-of-sale materials (POSM), shelf displays, and field force incentives. And at the center of it all, a fundamental management nightmare: **the retail blind spot**.",
      "Historically, FMCG executives, trade marketing managers, and regional leads made multi-million-dollar distribution decisions based on static paper forms, manual Excel dumps, and self-reported field audits. The operational leakage was staggering — costing brands upwards of $50,000 a month across large store networks in unverified displays, misplaced inventory, and biased reporting.",
      "When we set out to build **U-Lens** at The Data Island, our directive was simple to state, yet immensely complex to engineer: eliminate the guesswork, and convert raw, in-store smartphone photos into real-time operational command.",
      "Here is the story of how we designed, architected, and deployed U-Lens — from solving sub-second computer vision constraints to automating field force payroll.",
      "---",
      "## The Core Problem: The 15-Minute Audit Friction",
      "When we conducted our initial field research shadowing merchandisers, we saw the exact point where traditional systems fail.",
      "A field agent walks into a crowded store, navigates cramped aisles, manually counts hundreds of individual SKUs on a shelf, measures Share of Shelf (SOS) with a ruler or an estimate, fills out a 20-question mobile form, checks off POSM conditions, and uploads three separate photos.",
      "- **Time spent per store:** 10 to 15 minutes\n- **Data accuracy:** Unreliable and heavily biased\n- **Field agent sentiment:** Frustrated by administrative burden during tight route schedules",
      "If an audit takes 15 minutes, field coverage drops. If data entry is manual, agents default to estimation. To fix retail execution, we realized we couldn't just build a \"better form app.\" We had to eliminate manual logging entirely.",
      "---",
      "## Product Blueprint: One Photo. One Second. Total Intelligence.",
      "We anchored the U-Lens product strategy around a central design constraint: **the agent snaps one photo, and the AI does everything else in under a second.**",
      "To achieve this, we architected U-Lens across three core software layers:",
      "| Layer | Capabilities |\n|---|---|\n| **1. Merchandiser Mobile App** | 1-second AI shelf scan · Dynamic route & PJP navigation · Real-time on-site feedback |\n| **2. Supervisor Management App** | Live GPS check-ins & routes · AI challenge mechanism · Joint-call & coaching logs |\n| **3. Central Executive Portal** | Territory & user hierarchy · AI model retraining pipeline · Automated incentive payroll |",
      "### 1. The Computer Vision Pipeline",
      "When a merchandiser captures a shelf photo, our custom object detection and segmentation models immediately generate visual bounding boxes around every visible item.",
      "- **600+ SKU recognition:** The engine identifies brand SKUs alongside competitor products instantly, mapping exact Share of Shelf percentages.\n- **POSM & planogram compliance:** The system verifies whether shelf talkers, standees, and danglers are correctly positioned and undamaged.\n- **Exclusivity rules:** If a competitor's product creeps into dedicated brand shelf space, violating an agreed-upon planogram, the AI triggers an instant exclusivity alert.",
      "### 2. AI Voice Pitch Verification",
      "Retail execution isn't just visual — it's conversational. We integrated an in-app AI voice detection module that analyzes field sales pitches during store visits. This keeps brand messaging aligned with active promotional campaigns while eliminating under-the-table side deals between field reps and shopkeepers.",
      "### 3. Closing the Quality Loop: Supervisor Challenges",
      "No AI model is perfect on day one, especially under poor store lighting or when packaging changes. We built an AI challenge mechanism directly into the Supervisor App: if an audit is flagged as \"failed\" or misidentifies a new SKU, the supervisor submits a challenge remark. This automatically routes the image into our continuous model retraining pipeline, making the system smarter every week.",
      "---",
      "## The Big Win: Automating Performance-Based Payroll",
      "One of the biggest product breakthroughs with U-Lens was bridging the gap between audit data and payout execution.",
      "Historically, calculating month-end field force incentives meant weeks of manual reconciliation between HQ supervisors, regional managers, and finance teams. Disputes were frequent, and field morale suffered.",
      "With U-Lens, we turned execution integrity into a direct mathematical formula. Because every store audit is geotagged, time-stamped, and verified by computer vision, month-end incentive payouts now auto-calculate based entirely on real, verified KPI execution data.",
      "**The result?** Zero month-end payroll disputes, reduced administrative overhead, and a field force incentivized by transparent performance metrics.",
      "---",
      "## Lessons Learned Building Enterprise AI for Emerging Markets",
      "1. **Build for low connectivity first.** Rural retail zones mean spotty network signals. U-Lens was architected with an offline-first mobile engine, letting agents capture and log audits seamlessly offline, then auto-sync once back in range.\n2. **Respect the field agent's workflow.** Software designed at a desk often fails on the street. Lowering the audit time from 15 minutes to under 1 second transformed the app from a \"surveillance tool\" into a daily assistant for field teams.\n3. **Data hygiene is everything.** Standardizing data across enterprise systems — down to strict pipeline rules like lowercased email records and unified SKU naming conventions — is what separates a fragile prototype from an enterprise-grade platform handling 45,000+ daily scans.",
      "---",
      "## Looking Ahead",
      "Building U-Lens proved that when you pair computer vision with seamless field UX, you don't just digitize old processes — you fundamentally change how trade marketing operates.",
      "By replacing paper estimates with instant AI-powered data, enterprise brands can finally stop guessing where their products are, start protecting their display investments, and gain absolute operational control over their retail footprint.",
    ],
  },
  {
    slug: "openai-gpt-6-astra-launch",
    title: "OpenAI Launches GPT-6 Astra, Claiming New Records in Reasoning, Coding, and Computer Use",
    category: "News",
    excerpt:
      "OpenAI's new flagship model posts record benchmark scores and crosses a critical cybersecurity capability threshold, rolling out first to a limited set of organizations.",
    image: "/article/astra.png",
    author: "Albid Nawar",
    authorImage: "/images/design-mode/63407fbdc2d4ac5270385fd4_home-he.png",
    date: "Sep 2, 2026",
    content: [
      "OpenAI has introduced GPT-6 Astra, a new flagship model the company is positioning as its most capable and most aligned release to date. The model is rolling out first to a limited set of organizations, with broader access for ChatGPT Plus, Pro, Business, and Enterprise users, as well as through the OpenAI API, Microsoft Azure, and AWS Bedrock, expected in the coming days.",
      "## Benchmark Claims",
      "OpenAI reports that Astra sets new highs across a wide range of evaluations, including a 98% score on FrontierMath Tier 4, a 99.9% score on the ARC-AGI-3 reasoning benchmark, and a perfect 100% on ExploitBench, a benchmark that measures cybersecurity exploit development. The company also says the model has already contributed to solving previously unsolved problems in mathematics.",
      "Greg Kamradt of the ARC Prize Foundation, which administers the ARC-AGI benchmarks, said Astra effectively reached \"human parity\" on ARC-AGI-3, calling it a meaningful step change in frontier-model performance.",
      "OpenAI also says Astra is significantly faster and cheaper to run than its predecessor, GPT-5.6 Sol, on many tasks. On one internal computer-use benchmark, the company reports the new model scored higher while taking roughly 40 minutes per task on average, compared with about 75 minutes for GPT-5.6 Sol.",
      "## Computer Use and Everyday Office Work",
      "A central theme of the release is autonomous computer use. OpenAI says Astra can fill out online forms, update CRM records, manage calendars, conduct research and draft summaries, analyze scientific data and generate plots, build and QA-test websites, and troubleshoot software largely on its own. The company also highlights improvements in document, spreadsheet, and slide-deck generation, saying the model does a better job matching a user's existing templates and writing style rather than producing generic output.",
      "Third-party partners echoed those claims. Cognition, maker of the AI coding tool Devin, said it is integrating Astra into its product at launch and saw clearer testing output as a result. Legal AI company Harvey said the model approaches legal work more like an experienced attorney would, distinguishing verified records from unsupported claims and turning ambiguities into concrete drafting decisions.",
      "## Coding and Science",
      "OpenAI describes Astra as its strongest model yet for software engineering, pointing to gains on benchmarks such as Terminal-Bench 4.0 and DeepSWE, and introducing a new \"notes\" feature in its Codex tool that lets the model retain context across long sessions instead of repeatedly summarizing earlier work.",
      "On the scientific side, OpenAI says Astra helped improve long-standing mathematical bounds related to gaps between prime numbers, and posted new highs on health- and life-science-related evaluations, including GPQA Diamond and HealthBench Professional.",
      "## Cybersecurity: Capability and Guardrails",
      "OpenAI disclosed that Astra crosses what it calls the \"Critical\" threshold for cybersecurity capability under its internal Preparedness Framework, meaning the model can identify and develop working exploits — including previously unknown vulnerabilities — at a level well beyond its predecessor. In testing without production safeguards, the company says the model discovered and used two previously unknown vulnerabilities, which it is now disclosing to the affected software maintainers.",
      "Because of this, OpenAI says the publicly available version of Astra is restricted from carrying out more advanced offensive cybersecurity tasks, such as building proof-of-concept exploits, though the company plans to loosen those restrictions for vetted defensive use cases through a program it calls OpenAI Daybreak.",
      "## Alignment and Safety",
      "OpenAI frames Astra as its most aligned model to date, saying it is less likely to exceed its intended task scope, attempt to bypass review safeguards, or make misleading claims about its own capabilities compared with GPT-5.6 Sol. As one test of this, the company built an evaluation — informed by an earlier real-world incident — to check whether a model would overstep its authorized scope when faced with a difficult or impossible task. OpenAI reports Astra did so in none of the tested cases, versus 48% of the time for its predecessor.",
      "The company says it is also deploying additional misalignment-monitoring systems in production for Astra-class models and continuing to publish detailed findings in an accompanying system card.",
      "## Availability and Pricing",
      "GPT-6 Astra is available in the OpenAI API under the name gpt-6-astra, with standard pricing set at $10 per million input tokens and $50 per million output tokens; a faster processing mode is available at twice the price. Enterprise administrators can enable the model for their organization, though it is off by default at launch. A more capable \"Astra Pro\" tier is also being made available to Pro, Business, and Enterprise subscribers.",
    ],
  },
  {
    slug: "harness-engineering-resource-guide",
    title: "Harness Engineering: A Practical Guide to Building Reliable AI Agents",
    category: "Resources",
    excerpt:
      "What harness engineering is, why it emerged, what a harness actually contains, and how teams use it to turn impressive agent demos into systems that hold up in real workflows.",
    image: "/images/Gemini_Generated_Image_7wof787wof787wpp.png",
    author: "Albid Nawar",
    authorImage: "/images/design-mode/63407fbdc2d4ac5270385fd4_home-he.png",
    date: "Aug 25, 2026",
    content: [
      "Most AI agents that fail in production don't fail because the underlying model is weak. They fail because nothing was built around the model to keep it on track. In 2026, the discipline that addresses this gap finally has a name: **harness engineering**.",
      "This guide explains what harness engineering is, why it emerged, what a harness actually contains, and how teams are using it to turn impressive demos into agents that hold up in real workflows.",
      "## What Is a Harness?",
      "The industry has converged on a simple formula: **Agent = Model + Harness.**",
      "The model supplies raw reasoning ability. The harness is everything else — the tools the agent can call, the permissions that limit what it's allowed to touch, the checks that catch its mistakes, the memory that keeps it oriented across a long task, and the observability layer that lets a human see what it's doing. A harness is not the agent itself; it's the runtime structure that turns a powerful but unpredictable model into something an organization can actually trust to act.",
      "The term traces back to a habit HashiCorp co-founder Mitchell Hashimoto described in a February 2026 post: every time his coding agent made a mistake, he engineered a permanent fix into its environment rather than just hoping it wouldn't happen again. Within weeks, engineering teams at OpenAI, Anthropic, and elsewhere had published their own accounts of the same underlying discipline, and \"harness engineering\" stuck as the shorthand for it.",
      "## Why the Model Stopped Being the Bottleneck",
      "For a while, improving an agent meant swapping in a better model or writing a cleverer prompt. That's no longer where the biggest gains come from.",
      "The clearest evidence is a widely cited case from the LangChain engineering team, which moved its coding agent from 30th to 5th place on a Terminal-Bench leaderboard in March 2026 without changing the underlying model at all — the entire improvement came from restructuring the harness around it. Industry surveys tell a similar story: LangChain's 2026 State of AI Agents report found that more than half of organizations now have agents in production, yet quality — not model capability, not cost — is cited most often as the barrier to going further. Separate analysis of enterprise agent rollouts suggests only a small fraction of agent projects that get built ever make it past the prototype stage, and Gartner has projected that a large share of agentic AI initiatives will be shelved by 2027 due to unclear value and weak controls, not underpowered models.",
      "## Failure Modes a Harness Is Designed to Catch",
      "Anthropic's research into agent behavior has helped name several failure patterns that are common across models but fixable at the harness level, including:",
      "- **Victory declaration bias** — an agent marks a task complete without actually verifying the result.\n- **Context anxiety** — as its context window fills up, an agent rushes and cuts corners to avoid running out of space.\n- **One-shotting overreach** — an agent tries to solve an entire problem in a single pass, producing a large, undocumented tangle of changes instead of reviewable steps.",
      "None of these are solved by asking the model to \"try harder.\" They're solved by changing what the agent is allowed to do, what it's shown, and what checks its output has to pass before it's considered finished.",
      "## The Anatomy of a Harness",
      "Different teams describe the internals slightly differently, but most converge on the same three functions.",
      "**An information layer** controls what the agent can see and which tools it's authorized to call at any given moment. Agents can only reason about what's actually in front of them — context living in a chat thread, a colleague's head, or an undocumented decision is invisible to the system, no matter how important it is.",
      "**An execution layer** intercepts what the model proposes before it becomes a real-world action. This is where guardrails live: deterministic, rule-based checks (linters, schema validation, unit tests) that run fast and cheap on every step, alongside slower, judgment-based checks — often another model acting as a reviewer — reserved for cases that need real semantic evaluation rather than a fixed rule.",
      "**A feedback layer** captures what happens when something goes wrong — a rejected pull request, a failed test, a human correction — and feeds it back into the agent's working context so the same mistake doesn't recur on the next attempt. Over many iterations, this is what lets an agent's error rate keep dropping instead of staying flat.",
      "## Inner Harness vs. Outer Harness",
      "It helps to separate two layers of responsibility. Model providers build the **inner harness**: native tool-calling, context windows, and baseline safety behavior built directly into the model and its official SDK. Application teams build the **outer harness** on top of that: the specific tools, permission rules, testing setup, and domain guardrails that map a general-purpose model onto one organization's actual workflow.",
      "The inner harness is roughly the same for every user of a given model. The outer harness is where the real engineering effort — and the real competitive advantage — sits.",
      "## What This Looks Like in Practice",
      "A few production examples illustrate the range of what harness engineering covers:",
      "- **Repository-as-context.** OpenAI's own engineering team, building an agent-first internal product almost entirely with its Codex agent, found that anything not discoverable directly in the repository — a Slack discussion, a decision made only in a meeting — was effectively invisible to the agent. Their fix was to push more of that institutional knowledge into versioned, in-repo artifacts the agent could actually read, and to encode recurring mistakes as explicit rules the agent would keep re-reading rather than something a human had to keep re-explaining.\n- **Incident response at scale.** Microsoft's Azure SRE Agent wires an agent harness together from monitoring tools, code repositories, and incident-management systems, with a human-in-the-loop for high-stakes decisions. Internally, it's credited with cutting the average time to mitigate a production incident dramatically compared with manual response.\n- **Long-running, resumable work.** Meta's internal ad-ranking automation system uses a harness capable of pausing and resuming multi-day pipelines, preserving context across a \"hibernate and wake\" cycle so long tasks don't lose coherence between sessions.",
      "The common thread isn't a specific tool or vendor — it's the same discipline applied to very different problems: constrain what the agent can do, give it the information it actually needs, verify its work before trusting it, and make sure a mistake, once caught, can't happen the same way twice.",
      "## How This Relates to Other Disciplines",
      "Harness engineering doesn't replace prompt engineering or context engineering — it builds on both. Prompt engineering is about getting a good single response out of a model. Context engineering is about curating what information reaches the model in the first place. Harness engineering sits a layer above: it governs what happens *around* the entire interaction — before, during, and after the model produces output — so that reliability doesn't depend on getting a prompt exactly right every time.",
      "It also overlaps with, but isn't the same as, MLOps and DevOps. MLOps is concerned with a model's performance over its lifecycle — training, retraining, drift. Harness engineering is concerned with an agent's behavior in real-time execution. DevOps principles around CI/CD and infrastructure reproducibility carry over directly, just applied to agent behavior instead of software deployment pipelines.",
      "## Getting Started: Principles for Building a First Harness",
      "Teams building their first serious agent harness tend to converge on a similar checklist:",
      "1. **Give the agent narrow, explicit tools** rather than broad, ambiguous ones — and make the permission boundaries for each tool explicit.\n2. **Separate cheap, deterministic checks from expensive, judgment-based ones**, and run the cheap ones on every step so problems surface early.\n3. **Treat every real failure as a permanent fix**, not a one-off. When an agent makes a mistake, the goal is to change the harness so that specific mistake becomes structurally difficult to repeat.\n4. **Push institutional knowledge into a place the agent can actually read** — versioned files, not chat threads or tribal memory.\n5. **Keep a human in the loop at genuinely high-stakes decision points**, while letting the agent operate autonomously everywhere else.\n6. **Instrument everything.** Logging, observability, and clear audit trails are what make it possible to diagnose *why* an agent failed instead of just noticing that it did.",
      "## The Road Ahead",
      "Harness engineering is a young discipline — the term itself has only been in wide use since early 2026 — but the underlying principles are already well established, and they don't depend on which model or which vendor's tooling a team happens to use. Whether the agent runs on Codex, Claude, Gemini, or an in-house stack, the same questions apply: what can it see, what can it do, how is its work checked, and what happens when it's wrong.",
      "As agents take on larger and more autonomous slices of real work, the gap between a good demo and a trustworthy production system is increasingly a harness gap, not a model gap. That makes harness engineering less a niche technique and more a core skill for any team shipping AI agents that need to actually be relied upon.",
    ],
  },
]

export function getArticle(slug: string) {
  return articles.find((article) => article.slug === slug)
}
